name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push frontend image
        run: |
          docker build -t rnutro/packyourbags-main-frontend:latest ./front-end
          docker push rnutro/packyourbags-main-frontend:latest

      - name: Build and push backend image
        run: |
          docker build -t rnutro/packyourbags-main-backend:latest ./back-end
          docker push rnutro/packyourbags-main-backend:latest

  